### ISSUE TITLE
Current models deprecated

### ISSUE THREAD

**Issue by TheCatchyName** [HaroldPetersInskipp/node-red-contrib-chatgpt#20]
Good day, I believe OpenAI has shutdown some of the models that are baked into the node, e.g. "text-davinci-003". Could you update the configuration?

Also, it would be helpful for future-proofing if you added a user configuration option to specify the whole endpoint URL and model choice.

Cheers!

**Comment by AlainGeenrits** [comment]
Same problem here...

**Comment by HaroldPetersInskipp** [comment]
The default behavior in v1.3.0 should now be set to use the model GPT-4o.
