### ISSUE TITLE
Model deprecated: text-davinci-003

### ISSUE THREAD

**Issue by mitdesai** [HaroldPetersInskipp/node-red-contrib-chatgpt#22]
I get this error when setting completion topic.

"The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations"

Based on the URL, this may need to be updated to gpt-3.5-turbo-instruct

**Comment by HaroldPetersInskipp** [comment]
The default behavior in v1.3.0 should now be set to use the model GPT-4o.
