### ISSUE TITLE
version 1.3.3 not work

### ISSUE THREAD

**Issue by shinichikudo18** [HaroldPetersInskipp/node-red-contrib-chatgpt#25]
"Cannot read properties of undefined (reading 'choices')", i only have this message

**Comment by HaroldPetersInskipp** [comment]
I've pushed an update that should fix this but I have no way to test it right now, if you could let me know if it works I would greatly appreciate it.

**Comment by shinichikudo18** [comment]
now is working with the version 1.3.4, thank you

**Comment by HaroldPetersInskipp** [comment]
Thank you for the confirmation.
