### ISSUE TITLE
Storing Credentials

### ISSUE THREAD

**Issue by HaroldPetersInskipp** [HaroldPetersInskipp/node-red-contrib-chatgpt#5]
**Description**

API keys should be defined as credentials and stored separately to the main flow file so they do not accidentally get included if a user exports a flow from the editor without removing them manually.

The following documentation can used to implement this feature in an elegant way: https://nodered.org/docs/creating-nodes/credentials

**Comment by HaroldPetersInskipp** [comment]
Credentials are now stored properly so as not to be accidentally exported with a flow

**Comment by peterpanstechland** [comment]
Hi, I am trying to setup the credentials and this is the first time trying this method and i have install the "
node-red-contrib-credentials" node and tried to set API_KEY and Organization, like the following image shows. but i still getting the api key errors. Please help me. Thanks
![2024-01-17_20-51](https://github.com/HaroldPetersInskipp/node-red-contrib-chatgpt/assets/4452826/404a55cc-8f02-4423-ab4a-88f016598989)

**Comment by HaroldPetersInskipp** [comment]
That's because those were not supported message properties. However, I have published an update to the node on npm that should resolve your issue by supporting the properties `msg.API_KEY` and `msg.ORGANIZATION` (all caps), let me know if you run into any further issues.

**Comment by peterpanstechland** [comment]
Hi I have tried again now I am getting the config.topic empty error and i have fixed it with a PR https://github.com/HaroldPetersInskipp/node-red-contrib-chatgpt/pull/19 please have a look and probably merge it, thanks.

**Comment by HaroldPetersInskipp** [comment]
Could you post the error exactly as shown? Did you select a topic in the nodes configuration menu or `read from msg.topic`, and if so did you send a valid topic on the `msg.topic` property?

**Comment by peterpanstechland** [comment]
I think something went wrong with my node-red, the node configuration menu did not show up for this. and i guess this is why i am struggling.

**Comment by peterpanstechland** [comment]
I tried reintall this node and seems everything is normal now, sorry for the trouble. 
![2024-01-18_12-51](https://github.com/HaroldPetersInskipp/node-red-contrib-chatgpt/assets/4452826/ec70af4d-3f17-45ed-83cc-a7244223e37e)
