### ISSUE TITLE
Option to select model with `msg.model`

### ISSUE THREAD

**Issue by HaroldPetersInskipp** [HaroldPetersInskipp/node-red-contrib-chatgpt#9]
Allow users to select the model to be used with a message property such as `msg.model`, so that going forward any model can be selected without needing additional support. Additionally, the nodes help dialog should contain a maintained up-to-date list of models that can be used with this node.

**Comment by HaroldPetersInskipp** [comment]
A sensible default option or user set option in the nodes edit dialog may be a good requirement as well.

**Comment by andrea-tomassi** [comment]
Any ETA for this? It would be a great feature!

**Comment by asktimfisher** [comment]
Came here to leave the exact same suggestion! This is a new feature that could future-proof this node for some time.

**Comment by livingmydesign** [comment]
with all the new models coming out, this would be a great improvement

**Comment by AlainGeenrits** [comment]
second that

**Comment by HaroldPetersInskipp** [comment]
`msg.model` is now a supported property to select any chat model going forward.
